version: "3.7"
services:
    traefik:
        image: traefik:v2.5.6
        restart: always
        network_mode: "host"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=true"
            # use true  docker container names which uses underscores. Edge case g.g. foo-bar_baz do not work yet
            - '--providers.docker.defaultrule=Host(`{{ .Name |  replace  "-" "_" }}.localhost`)'
            - "--entrypoints.web.address=:80"

    portainer:
        image: portainer/portainer:1.24.2-alpine
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
            - "traefik.http.routers.portainer.entrypoints=web"

    rstudio:
        image: rocker/verse:4.1.2
        restart: always
        volumes:
            - /:/host
            - $HOME:/home/rstudio
            - rstudio-site-library:/usr/local/lib/R/site-library
        environment:
            - DISABLE_AUTH=true
            - USERID=${UID}
            - GROUPID=${GID}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.rstudio.rule=Host(`rstudio.localhost`)"
            - "traefik.http.routers.rstudio.entrypoints=web"

volumes:
    rstudio-site-library:
